all:
	@echo "make unix for unix compile; make win for std compile"

unix:
	@gcc 23-6-2021.c ../lib/sem_tools.c -o prog -Wextra -Wall

unix-debug:
	@gcc 23-6-2021.c ../lib/sem_tools.c -o prog -Wextra -Wall -D debug

