all:
	gcc 23-1-2019.c -o prog -Wall -Wextra -lpthread
	gcc 23-1-2019_sysv.c -o prog_sysv -Wall -Wextra -lpthread

sem:
	gcc 23-1-2019.c -o prog -Wall -Wextra -lpthread

system_v_sem:
	gcc 23-1-2019_sysv.c -o prog_sysv -Wall -Wextra -lpthread