all:
	gcc 17-10-2019.c -o prog_std -Wall -Wextra -lpthread

mutex_var:
	gcc 17-10-2019.c -o prog_std -Wall -Wextra -lpthread -D __mutex_var

sem_var:
	gcc 17-10-2019.c -o prog_std -Wall -Wextra -lpthread -D __sem_var

